config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # get '/',to: "pages#home"
  
  get '/about', to: "pages#about"
  
  get '/signup', to: "users#new"
  # post '/users', to: "users#create"
  resources :users, except: [:new]

  resources :articles do #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
  end 
  resources :mentions, only: [:index]
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :categories , except: [:destroy]

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def show
    # @article = Article.find(params[:id]) this instance variavle available in articles#show view
  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article] # shows {"title"=>"zghf", "description"=>"zdghxd"}
    # render plain: @article # shows #<Article:0x00007f9460106908> // @article.inspect
    @article = Article.new(article_params)
    @article.user = curr_user # a user must be logged in to create a new article
    if @article.save 
      flash[:notice] = "Article Created Successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    # @article= Article.find(params[:id])
  end

  def update
    # @article= Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article Updated Successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end 
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def require_same_user
    if curr_user != @article.user && !curr_user.admin?
      flash[:alert] = "You are not allowed to edit this article"
      redirect_to article_path(@article)
    end
  end

end

app/views/articles/_article.html.erb
<% @articles.order(:id).each do |article| %>
		<div class="row justify-content-center">
			<div class="col-md-8 my-3">
				<div class="card text-center shadow bg-white rounded">
					<div class="card-header font-italic">
            <% if article.user  %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
            <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
					<div class="card-body">
						<h5 class="card-title">
							<%= link_to "#{article.title}", article_path(article), class:
							"text-success" %>
						</h5>
						<p class="card-text">
							<%= truncate(article.description, length: 100) %>
						</p>
						<%= link_to "view", article_path(article), class: "btn btn-outline-success" %> 
            <% if logged_in? && (article.user == curr_user || curr_user.admin?) %>
              <%= link_to "edit", edit_article_path(article), class: "btn btn-outline-primary ml-2" %>
              <%= link_to "Delete", article_path(article), method: :delete,
                                                          data: {confirm: 'Are you sure?'},
                                                          class: "btn btn-outline-danger ml-2" %>
            <% end %>
					</div>
					<div class="card-footer text-muted">
						<small
							>Created <%= time_ago_in_words(article.created_at) %> ago &
							updated <%= time_ago_in_words(article.updated_at) %> ago
						</small>
					</div>
				</div>
			</div>
		</div>
	<% end %>

app/views/articles/_form.html.erb
<div class="row justify-content-center text-white">
  <div class="col-md-10">
  
    <%= render "shared/errors", obj: @article %>

    <%= form_with(model: @article,class: "shadow p-4 bg-dark mb-2 rounded", local: true) do |f| %>
      <div class="form-group row">
          <%= f.label :title , class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
          </div>
      </div>
      <div class="form-group row">
          <%= f.label :description , class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
          </div>
      </div>

       <div class="form-group row">
          <%= f.label :category , class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= f.collection_select(:category_ids, Category.all, :id , :name, {prompt: 'make your selection from the list below(optional)'}, { multiple: true, class: 'custom-select '}  ) %>
          </div>
      </div>


      <div class="form-group row justify-content-center mb-0">
        <%= f.submit  class: "btn btn-outline-light btn-lg"%>  
      </div> 
    <% end  %>
  </div>
  <div class="mb-2">
    <%= link_to "[ Cancel & Return to Articles page ]", articles_path, class: "btn btn-outline-success" %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container mt-2"> 
  <h3></h3>
  <h4 class="text-center">Edit Article</h4>
  <%= render "form" %>
</div>

app/views/articles/index.html.erb
<div class="container pt-2 pb-5">
	<h1 class="text-center text-dark">Articles Listing Page</h1>

   <div class="flickr_pagination">
    <div class="page_info mb-2">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, container: false %> <%#, page_links: false %>
  </div>
  
  <%= render "article"%>

   <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %> <%#, page_links: false %>
  </div>
</div>
  

app/views/articles/new.html.erb
<div class="container mt-2"> 
  <h4 class="text-center text-dark">Create a New Article</h4>
  <%= render "form" %>
</div>

app/views/articles/show.html.erb
<div class="container p-2">
  <h3 class="text-center"><%= @article.title %></h3>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card text-center shadow bg-white rounded ">
        <div class="card-header font-italic">
         <p class="mb-2" > by <%= @article.user.username%></p>
          <%= link_to gravatar_for(@article.user, size:50), user_path(@article.user)%>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left">
            <%= simple_format(@article.description) %>
          </div>
          <%= link_to "back", articles_path, class: "btn btn-outline-success btn-sm " %>
          <% if logged_in? && (@article.user == curr_user || curr_user.admin?) %>
            <%= link_to "edit", edit_article_path(@article), class: "btn btn-outline-primary btn-sm ml-2" %>
            <%= link_to "Delete", article_path(@article), method: :delete,
                                                        data: {confirm: 'Are you sure?'},
                                                        class: "btn btn-outline-danger btn-sm ml-2" %>
          <% end %>
        </div>
        <div class="card-footer text-muted py-1">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago &
            updated <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>  
  </div>
  <hr/>
  <div class="row">
    <div class="col-6">
      <h6><%= pluralize(@article.comments.size, "Comment") %></h6>
      <div class="comments">
        <%= render @article.comments %>
      </div>
    </div>
    <div class="col-6">
      <%= render "comments/form" %>
    </div>
  </div>
</div>