config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # get '/',to: "pages#home"
  
  get '/about', to: "pages#about"
  
  get '/signup', to: "users#new"
  # post '/users', to: "users#create"
  resources :users, except: [:new]

  resources :articles do #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:create]
  end 
  resources :mentions, only: [:index]
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :categories , except: [:destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: { case_sensitive: false}, length: {minimum: 3 , maximum:20}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :require_admin, except: [:index, :show]
before_action :set_category, only: [:show, :edit, :update]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3)
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render "new"
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page:2)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category updated successfully!"
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
  def category_params
    params.require(:category).permit(:name)
  end
  def require_admin
    if !(logged_in? && curr_user.admin?)
      flash[:alert] = "You are not authorized to continue"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1 p-2" %>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<%= form_with(model: @category, class: "shadow p-4 bg-dark mb-2 rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name ,"Category Name", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter an Name" %>
    </div>
  </div>
  <div class="form-group row justify-content-center mb-0">
    <%= f.submit class: "btn btn-outline-light btn-lg"%>  
  </div> 
<% end  %>

app/views/categories/edit.html.erb
<div class="container mt-2"> 
  <h4 class="text-center text-dark">Edit category</h4>
  <div class="row justify-content-center text-white">
    <div class="col-md-10">
      <%= render "form" %>
    </div>
    <div class="mb-2">
    <%= link_to "[ Cancel & Return to Category page ]", category_path(@category),
                                                       class: "btn btn-outline-success" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container pt-2 pb-5">
	<h3 class="text-center text-dark">Categories</h3>

  <div class="flickr_pagination">
    <div class="page_info mb-2">
      <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, container: false %>
  </div>

  <% @categories.each do |category| %>
		<div class="row justify-content-center">
			<div class="col-md-5 my-3">
				<div class="card text-center shadow bg-white rounded">
					<div class="card-body">
						<h5 class="card-title">
							<%= link_to "#{category.name}", category_path(category), class: "text-success" %>
						</h5>
            <p class="card-text">
							<%= pluralize(category.articles.size, 'article') %>
						</p>
					</div>
					<div class="card-footer text-muted">
						<small
							>Created <%= time_ago_in_words(category.created_at) %> ago &
							updated <%= time_ago_in_words(category.updated_at) %> ago
						</small>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/categories/new.html.erb
<div class="container mt-2"> 
  <h4 class="text-center text-dark">Create a new category</h4>
  <div class="row justify-content-center text-white">
    <div class="col-md-10">
    
      <%= render "form" %>
    </div>
    <div class="mb-2">
    <%= link_to "[ Cancel & Return to Categories listing ]", categories_path,
                                                       class: "btn btn-outline-success" %>
    </div>
  </div>

</div>

app/views/categories/show.html.erb
<div class="container p-2">

  <h3 class="text-center text-dark">Category: <%= @category.name %></h3>

  <% if logged_in? && curr_user.admin? %>
    <div class="text-center mt-2">
      <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-primary"%>   
    </div>
  <% end %>

  <h5 class="text-center text-dark mt-4">Articles</h5>

  <div class="flickr_pagination">
    <div class="page_info mb-2">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, container: false %> <%#, page_links: false %>
  </div>

  <%= render "articles/article" %>

  <div class="flickr_pagination">
    <%= will_paginate @articles, container: false %> <%#, page_links: false %>
  </div>
</div>